message_bus:
  host: 127.0.0.1
  port: 4222
  username:
  password:

warden:
  socket: /tmp/warden.sock
  containers: /opt/warden/containers

state_file: /tmp/narc.json

advertise_interval: 10

capacity:
  memory: 2047
  disk: 16384